name: build

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            git
            make
            cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-libxml2
            mingw-w64-x86_64-libwmf
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-fontconfig
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-librevenge
            mingw-w64-x86_64-libvisio
            mingw-w64-x86_64-ntldd
            gawk

      # Build libemf2svg from the Windows-friendly fork (no symlink drama)
      - name: Build libemf2svg (dep)
        run: |
          set -e
          git clone --depth=1 https://github.com/metanorma/libemf2svg
          cmake -S libemf2svg -B libemf2svg/build -G "Unix Makefiles" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/mingw64 \
            -DLONLY=on -DSTATIC=on \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.10 \
            -DCMAKE_CXX_FLAGS="-static-libgcc -static-libstdc++"
          cmake --build libemf2svg/build -- -j
          cmake --install libemf2svg/build

      - name: Configure & build libvisio2svg
        run: |
          set -e
          cmake -S . -B build -G "Unix Makefiles" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/mingw64 \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.10 \
            -DCMAKE_CXX_FLAGS="-static-libgcc -static-libstdc++"
          cmake --build build -- -j
          cmake --install build

      - name: Bundle portable artifacts (EXEs + DLLs)
        run: |
          set -e
          mkdir -p dist
          for exe in /mingw64/bin/vsd2svg-conv.exe /mingw64/bin/vss2svg-conv.exe; do
            cp "$exe" dist/
            ntldd -R "$exe" | gawk '/mingw64/ {print $3}' | sort -u | xargs -r -I{} cp {} dist/
          done

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libvisio2svg-windows-portable
          path: dist/**
